org: wilkcaetano
app: create-users

custom: ${file(serverless-env.yml)}

service: creations
provider:
  name: aws
  runtime: nodejs12.x
  environment:
    DB_URL: ${self:custom.DB_URL}
    NODE_ENV: ${self:custom.NODE_ENV}

plugins:
  - serverless-plugin-typescript 
  - serverless-offline

package:
  exclude:
    - config/.env.stg
    - config/.env.pro
  include:
    - config/.env.dev

functions:
  createUser:
    handler: app/handlers/userHandlers.create
    events:
      - http:
          path: users
          method: post
  getUserAll:
    handler: app/handlers/userHandlers.getAll
    events:
      - http:
          path: users
          method: get
  getUserOne:
    handler: app/handlers/userHandlers.getUserOne
    events:
      - http:
          path: users/{id}
          method: get              
          